package com.goodix.cap.fingerprint.sec.p001mt;

/* renamed from: com.goodix.cap.fingerprint.sec.mt.CmdIdBase */
public interface CmdIdBase {
    public static final int CAPTURE_FAILED = 4005;
    public static final int CAPTURE_SUCCESS = 4004;
    public static final int CMD_CAPTURE_FINGER_LEAVED = 4006;
    public static final int CMD_FALSE_TRIGGER_STATUS = 932;
    public static final int CMD_FDT_ZONE_8x1_PIXEL_NUM = 925;
    public static final int CMD_FDT_ZONE_8x7_PIXEL_NUM = 926;
    public static final int CMD_GET_INFO_CALIBRATION = 929;
    public static final int CMD_GET_INFO_DAC = 916;
    public static final int CMD_GET_INFO_IS_MODULE_PASS = 914;
    public static final int CMD_GET_INFO_PRODUCT_ID = 927;
    public static final int CMD_GET_INFO_TCODE = 915;
    public static final int CMD_GET_INFO_UID = 928;
    public static final int CMD_GET_SENSOR_INFO_END = 924;
    public static final int CMD_GET_SENSOR_INFO_START = 923;
    public static final int CMD_OTP_CHECK_END = 922;
    public static final int CMD_OTP_CHECK_START = 921;
    public static final int CMD_OTP_CHECK_TEST = 32;
    public static final int CMD_SATURATION_MAX = 930;
    public static final int CMD_SATURATION_MIN = 931;
    public static final int CMD_SENSOR_AVAILABLE_STATUS = 933;
    public static final int CMD_TOUCH_DATA_DIFFERENCE = 908;
    public static final int CMD_TOUCH_FALSE_IRQ = 911;
    public static final int CMD_TOUCH_INT_TEST = 24;
    public static final int CMD_TOUCH_LOCAL_PIXEL = 907;
    public static final int CMD_TOUCH_NOISE = 904;
    public static final int CMD_TOUCH_PERFORMANCE = 913;
    public static final int CMD_TOUCH_PIXEL_DOWN = 909;
    public static final int CMD_TOUCH_PIXEL_UP = 910;
    public static final int CMD_TOUCH_RST_TEST = 23;
    public static final int CMD_TOUCH_RUBBER_PLACEMENT = 912;
    public static final int CMD_TOUCH_SNR = 905;
    public static final int CMD_TOUCH_TEST_END = 920;
    public static final int CMD_TOUCH_TEST_START = 919;
    public static final int CMD_TOUCH_TOTAL_PIXEL = 906;
    public static final int CMD_TOUCH_WAITING = 902;
    public static final int CMD_TOUCH_WAITING_FAILED = 903;
    public static final int CMD_UNTOUCH_TEST_END = 918;
    public static final int CMD_UNTOUCH_TEST_START = 917;
    public static final int CMD_UN_TOUCH_LOCAL_PIXEL = 901;
    public static final int CMD_UN_TOUCH_PIXEL_SHORT = 72;
    public static final int CMD_UN_TOUCH_SPI_TEST = 8;
    public static final int CMD_UN_TOUCH_TOTAL_PIXEL = 900;
    public static final int ENROLL_STATUS = 5001;
    public static final int ENROLL_SUCCESS = 5002;
    public static final int IDENTIFY_FAILED = 6002;
    public static final int IDENTIFY_SUCCESS = 6001;
}
