package org.bouncycastle.asn1.pkcs;

import com.americanexpress.mobilepayments.hceclient.utils.common.HCEClientConstants;
import com.americanexpress.sdkmodulelib.util.Constants;
import com.samsung.android.spayfw.payprovider.discover.payment.data.DiscoverInAppCryptoData;
import com.samsung.android.spayfw.payprovider.visa.transaction.TransactionInfo;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier RC2_CBC;
    public static final ASN1ObjectIdentifier bagtypes;
    public static final ASN1ObjectIdentifier canNotDecryptAny;
    public static final ASN1ObjectIdentifier certBag;
    public static final ASN1ObjectIdentifier certTypes;
    public static final ASN1ObjectIdentifier crlBag;
    public static final ASN1ObjectIdentifier crlTypes;
    public static final ASN1ObjectIdentifier data;
    public static final ASN1ObjectIdentifier des_EDE3_CBC;
    public static final ASN1ObjectIdentifier dhKeyAgreement;
    public static final ASN1ObjectIdentifier digestAlgorithm;
    public static final ASN1ObjectIdentifier digestedData;
    public static final ASN1ObjectIdentifier encryptedData;
    public static final ASN1ObjectIdentifier encryptionAlgorithm;
    public static final ASN1ObjectIdentifier envelopedData;
    public static final ASN1ObjectIdentifier id_PBES2;
    public static final ASN1ObjectIdentifier id_PBKDF2;
    public static final ASN1ObjectIdentifier id_RSAES_OAEP;
    public static final ASN1ObjectIdentifier id_RSASSA_PSS;
    public static final ASN1ObjectIdentifier id_aa;
    public static final ASN1ObjectIdentifier id_aa_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_contentHint;
    public static final ASN1ObjectIdentifier id_aa_contentIdentifier;
    public static final ASN1ObjectIdentifier id_aa_contentReference;
    public static final ASN1ObjectIdentifier id_aa_encrypKeyPref;
    public static final ASN1ObjectIdentifier id_aa_ets_archiveTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_certCRLTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_certValues;
    public static final ASN1ObjectIdentifier id_aa_ets_certificateRefs;
    public static final ASN1ObjectIdentifier id_aa_ets_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_ets_contentTimestamp;
    public static final ASN1ObjectIdentifier id_aa_ets_escTimeStamp;
    public static final ASN1ObjectIdentifier id_aa_ets_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_ets_revocationRefs;
    public static final ASN1ObjectIdentifier id_aa_ets_revocationValues;
    public static final ASN1ObjectIdentifier id_aa_ets_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_ets_signerAttr;
    public static final ASN1ObjectIdentifier id_aa_ets_signerLocation;
    public static final ASN1ObjectIdentifier id_aa_msgSigDigest;
    public static final ASN1ObjectIdentifier id_aa_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_receiptRequest;
    public static final ASN1ObjectIdentifier id_aa_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_signatureTimeStampToken;
    public static final ASN1ObjectIdentifier id_aa_signerLocation;
    public static final ASN1ObjectIdentifier id_aa_signingCertificate;
    public static final ASN1ObjectIdentifier id_aa_signingCertificateV2;
    public static final ASN1ObjectIdentifier id_alg;
    public static final ASN1ObjectIdentifier id_alg_CMS3DESwrap;
    public static final ASN1ObjectIdentifier id_alg_CMSRC2wrap;
    public static final ASN1ObjectIdentifier id_alg_PWRI_KEK;
    public static final ASN1ObjectIdentifier id_ct;
    public static final ASN1ObjectIdentifier id_ct_TSTInfo;
    public static final ASN1ObjectIdentifier id_ct_authData;
    public static final ASN1ObjectIdentifier id_ct_authEnvelopedData;
    public static final ASN1ObjectIdentifier id_ct_compressedData;
    public static final ASN1ObjectIdentifier id_ct_timestampedData;
    public static final ASN1ObjectIdentifier id_cti;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfApproval;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfCreation;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfDelivery;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfOrigin;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfReceipt;
    public static final ASN1ObjectIdentifier id_cti_ets_proofOfSender;
    public static final ASN1ObjectIdentifier id_hmacWithSHA1;
    public static final ASN1ObjectIdentifier id_hmacWithSHA224;
    public static final ASN1ObjectIdentifier id_hmacWithSHA256;
    public static final ASN1ObjectIdentifier id_hmacWithSHA384;
    public static final ASN1ObjectIdentifier id_hmacWithSHA512;
    public static final ASN1ObjectIdentifier id_mgf1;
    public static final ASN1ObjectIdentifier id_pSpecified;
    public static final ASN1ObjectIdentifier id_smime;
    public static final String id_spq = "1.2.840.113549.1.9.16.5";
    public static final ASN1ObjectIdentifier id_spq_ets_unotice;
    public static final ASN1ObjectIdentifier id_spq_ets_uri;
    public static final ASN1ObjectIdentifier keyBag;
    public static final ASN1ObjectIdentifier md2;
    public static final ASN1ObjectIdentifier md2WithRSAEncryption;
    public static final ASN1ObjectIdentifier md4;
    public static final ASN1ObjectIdentifier md4WithRSAEncryption;
    public static final ASN1ObjectIdentifier md5;
    public static final ASN1ObjectIdentifier md5WithRSAEncryption;
    public static final ASN1ObjectIdentifier pbeWithMD2AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD2AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD5AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithMD5AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHA1AndDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHA1AndRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd128BitRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd128BitRC4;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd2_KeyTripleDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd3_KeyTripleDES_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd40BitRC2_CBC;
    public static final ASN1ObjectIdentifier pbeWithSHAAnd40BitRC4;
    public static final ASN1ObjectIdentifier pbewithSHAAnd40BitRC2_CBC;
    public static final ASN1ObjectIdentifier pkcs8ShroudedKeyBag;
    public static final ASN1ObjectIdentifier pkcs_1;
    public static final ASN1ObjectIdentifier pkcs_12;
    public static final ASN1ObjectIdentifier pkcs_12PbeIds;
    public static final ASN1ObjectIdentifier pkcs_3;
    public static final ASN1ObjectIdentifier pkcs_5;
    public static final ASN1ObjectIdentifier pkcs_7;
    public static final ASN1ObjectIdentifier pkcs_9;
    public static final ASN1ObjectIdentifier pkcs_9_at_challengePassword;
    public static final ASN1ObjectIdentifier pkcs_9_at_contentType;
    public static final ASN1ObjectIdentifier pkcs_9_at_counterSignature;
    public static final ASN1ObjectIdentifier pkcs_9_at_emailAddress;
    public static final ASN1ObjectIdentifier pkcs_9_at_extendedCertificateAttributes;
    public static final ASN1ObjectIdentifier pkcs_9_at_extensionRequest;
    public static final ASN1ObjectIdentifier pkcs_9_at_friendlyName;
    public static final ASN1ObjectIdentifier pkcs_9_at_localKeyId;
    public static final ASN1ObjectIdentifier pkcs_9_at_messageDigest;
    public static final ASN1ObjectIdentifier pkcs_9_at_signingDescription;
    public static final ASN1ObjectIdentifier pkcs_9_at_signingTime;
    public static final ASN1ObjectIdentifier pkcs_9_at_smimeCapabilities;
    public static final ASN1ObjectIdentifier pkcs_9_at_unstructuredAddress;
    public static final ASN1ObjectIdentifier pkcs_9_at_unstructuredName;
    public static final ASN1ObjectIdentifier preferSignedData;
    public static final ASN1ObjectIdentifier rc4;
    public static final ASN1ObjectIdentifier rsaEncryption;
    public static final ASN1ObjectIdentifier sMIMECapabilitiesVersions;
    public static final ASN1ObjectIdentifier safeContentsBag;
    public static final ASN1ObjectIdentifier sdsiCertificate;
    public static final ASN1ObjectIdentifier secretBag;
    public static final ASN1ObjectIdentifier sha1WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha224WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha256WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha384WithRSAEncryption;
    public static final ASN1ObjectIdentifier sha512WithRSAEncryption;
    public static final ASN1ObjectIdentifier signedAndEnvelopedData;
    public static final ASN1ObjectIdentifier signedData;
    public static final ASN1ObjectIdentifier srsaOAEPEncryptionSET;
    public static final ASN1ObjectIdentifier x509Certificate;
    public static final ASN1ObjectIdentifier x509Crl;
    public static final ASN1ObjectIdentifier x509certType;

    static {
        pkcs_1 = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        rsaEncryption = pkcs_1.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        md2WithRSAEncryption = pkcs_1.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        md4WithRSAEncryption = pkcs_1.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        md5WithRSAEncryption = pkcs_1.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        sha1WithRSAEncryption = pkcs_1.branch("5");
        srsaOAEPEncryptionSET = pkcs_1.branch("6");
        id_RSAES_OAEP = pkcs_1.branch("7");
        id_mgf1 = pkcs_1.branch("8");
        id_pSpecified = pkcs_1.branch("9");
        id_RSASSA_PSS = pkcs_1.branch(Constants.CLIENT_MINOR_VERSION);
        sha256WithRSAEncryption = pkcs_1.branch(HCEClientConstants.API_INDEX_TOKEN_REFRESH_STATUS);
        sha384WithRSAEncryption = pkcs_1.branch("12");
        sha512WithRSAEncryption = pkcs_1.branch("13");
        sha224WithRSAEncryption = pkcs_1.branch("14");
        pkcs_3 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        dhKeyAgreement = pkcs_3.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pkcs_5 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        pbeWithMD2AndDES_CBC = pkcs_5.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pbeWithMD2AndRC2_CBC = pkcs_5.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        pbeWithMD5AndDES_CBC = pkcs_5.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        pbeWithMD5AndRC2_CBC = pkcs_5.branch("6");
        pbeWithSHA1AndDES_CBC = pkcs_5.branch(Constants.CLIENT_MINOR_VERSION);
        pbeWithSHA1AndRC2_CBC = pkcs_5.branch(HCEClientConstants.API_INDEX_TOKEN_REFRESH_STATUS);
        id_PBES2 = pkcs_5.branch("13");
        id_PBKDF2 = pkcs_5.branch("12");
        encryptionAlgorithm = new ASN1ObjectIdentifier("1.2.840.113549.3");
        des_EDE3_CBC = encryptionAlgorithm.branch("7");
        RC2_CBC = encryptionAlgorithm.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        rc4 = encryptionAlgorithm.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        digestAlgorithm = new ASN1ObjectIdentifier("1.2.840.113549.2");
        md2 = digestAlgorithm.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        md4 = digestAlgorithm.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        md5 = digestAlgorithm.branch("5");
        id_hmacWithSHA1 = digestAlgorithm.branch("7");
        id_hmacWithSHA224 = digestAlgorithm.branch("8");
        id_hmacWithSHA256 = digestAlgorithm.branch("9");
        id_hmacWithSHA384 = digestAlgorithm.branch(Constants.CLIENT_MINOR_VERSION);
        id_hmacWithSHA512 = digestAlgorithm.branch(HCEClientConstants.API_INDEX_TOKEN_REFRESH_STATUS);
        pkcs_7 = new ASN1ObjectIdentifier("1.2.840.113549.1.7");
        data = new ASN1ObjectIdentifier("1.2.840.113549.1.7.1");
        signedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.2");
        envelopedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.3");
        signedAndEnvelopedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.4");
        digestedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.5");
        encryptedData = new ASN1ObjectIdentifier("1.2.840.113549.1.7.6");
        pkcs_9 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        pkcs_9_at_emailAddress = pkcs_9.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pkcs_9_at_unstructuredName = pkcs_9.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        pkcs_9_at_contentType = pkcs_9.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        pkcs_9_at_messageDigest = pkcs_9.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        pkcs_9_at_signingTime = pkcs_9.branch("5");
        pkcs_9_at_counterSignature = pkcs_9.branch("6");
        pkcs_9_at_challengePassword = pkcs_9.branch("7");
        pkcs_9_at_unstructuredAddress = pkcs_9.branch("8");
        pkcs_9_at_extendedCertificateAttributes = pkcs_9.branch("9");
        pkcs_9_at_signingDescription = pkcs_9.branch("13");
        pkcs_9_at_extensionRequest = pkcs_9.branch("14");
        pkcs_9_at_smimeCapabilities = pkcs_9.branch("15");
        id_smime = pkcs_9.branch("16");
        pkcs_9_at_friendlyName = pkcs_9.branch("20");
        pkcs_9_at_localKeyId = pkcs_9.branch("21");
        x509certType = pkcs_9.branch("22.1");
        certTypes = pkcs_9.branch("22");
        x509Certificate = certTypes.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        sdsiCertificate = certTypes.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        crlTypes = pkcs_9.branch("23");
        x509Crl = crlTypes.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        preferSignedData = pkcs_9.branch("15.1");
        canNotDecryptAny = pkcs_9.branch("15.2");
        sMIMECapabilitiesVersions = pkcs_9.branch("15.3");
        id_ct = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        id_ct_authData = id_ct.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        id_ct_TSTInfo = id_ct.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        id_ct_compressedData = id_ct.branch("9");
        id_ct_authEnvelopedData = id_ct.branch("23");
        id_ct_timestampedData = id_ct.branch("31");
        id_alg = id_smime.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        id_alg_PWRI_KEK = id_alg.branch("9");
        id_cti = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        id_cti_ets_proofOfOrigin = id_cti.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        id_cti_ets_proofOfReceipt = id_cti.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        id_cti_ets_proofOfDelivery = id_cti.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        id_cti_ets_proofOfSender = id_cti.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        id_cti_ets_proofOfApproval = id_cti.branch("5");
        id_cti_ets_proofOfCreation = id_cti.branch("6");
        id_aa = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        id_aa_receiptRequest = id_aa.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        id_aa_contentHint = id_aa.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        id_aa_msgSigDigest = id_aa.branch("5");
        id_aa_contentReference = id_aa.branch(Constants.CLIENT_MINOR_VERSION);
        id_aa_encrypKeyPref = id_aa.branch(HCEClientConstants.API_INDEX_TOKEN_REFRESH_STATUS);
        id_aa_signingCertificate = id_aa.branch("12");
        id_aa_signingCertificateV2 = id_aa.branch(Constants.TOKEN_META_DEVICEID_TAG);
        id_aa_contentIdentifier = id_aa.branch("7");
        id_aa_signatureTimeStampToken = id_aa.branch("14");
        id_aa_ets_sigPolicyId = id_aa.branch("15");
        id_aa_ets_commitmentType = id_aa.branch("16");
        id_aa_ets_signerLocation = id_aa.branch("17");
        id_aa_ets_signerAttr = id_aa.branch("18");
        id_aa_ets_otherSigCert = id_aa.branch("19");
        id_aa_ets_contentTimestamp = id_aa.branch("20");
        id_aa_ets_certificateRefs = id_aa.branch("21");
        id_aa_ets_revocationRefs = id_aa.branch("22");
        id_aa_ets_certValues = id_aa.branch("23");
        id_aa_ets_revocationValues = id_aa.branch("24");
        id_aa_ets_escTimeStamp = id_aa.branch("25");
        id_aa_ets_certCRLTimestamp = id_aa.branch("26");
        id_aa_ets_archiveTimestamp = id_aa.branch("27");
        id_aa_sigPolicyId = id_aa_ets_sigPolicyId;
        id_aa_commitmentType = id_aa_ets_commitmentType;
        id_aa_signerLocation = id_aa_ets_signerLocation;
        id_aa_otherSigCert = id_aa_ets_otherSigCert;
        id_spq_ets_uri = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        id_spq_ets_unotice = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        pkcs_12 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        bagtypes = pkcs_12.branch("10.1");
        keyBag = bagtypes.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pkcs8ShroudedKeyBag = bagtypes.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        certBag = bagtypes.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        crlBag = bagtypes.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        secretBag = bagtypes.branch("5");
        safeContentsBag = bagtypes.branch("6");
        pkcs_12PbeIds = pkcs_12.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pbeWithSHAAnd128BitRC4 = pkcs_12PbeIds.branch(TransactionInfo.VISA_TRANSACTIONTYPE_REFUND);
        pbeWithSHAAnd40BitRC4 = pkcs_12PbeIds.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_REFUNDED);
        pbeWithSHAAnd3_KeyTripleDES_CBC = pkcs_12PbeIds.branch(TransactionInfo.VISA_TRANSACTIONSTATUS_DECLINED);
        pbeWithSHAAnd2_KeyTripleDES_CBC = pkcs_12PbeIds.branch(DiscoverInAppCryptoData.DEFAULT_ECI_INDICATOR);
        pbeWithSHAAnd128BitRC2_CBC = pkcs_12PbeIds.branch("5");
        pbeWithSHAAnd40BitRC2_CBC = pkcs_12PbeIds.branch("6");
        pbewithSHAAnd40BitRC2_CBC = pkcs_12PbeIds.branch("6");
        id_alg_CMS3DESwrap = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
        id_alg_CMSRC2wrap = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
    }
}
